#cloud-config
package_update: true
package_upgrade: true

packages:
  - git
  - ansible

users:
  - name: ansible
    gecos: Ansible User
    groups: sudo, admin, wheel
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: true
    ssh_authorized_keys:
      - <your-ssh-public-key>
  - name: sly
    gecos: Sly User
    groups: sudo, admin, wheel
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: true
    ssh_authorized_keys:
      - <your-ssh-public-key>

runcmd:
  - [chown, -R, sly:sly, /home/sly]
  - [chown, -R, ansible:ansible, /home/ansible]
  - [usermod, -aG, syslog, ansible]
  - [
      sudo,
      -u,
      ansible,
      ansible-pull,
      -U,
      "https://github.com/mrjohnsly/sly.dev.git",
      -o,
      config/ansible/server-bootstrap.yml,
      -d,
      /home/ansible/sly.dev,
    ]

write_files:
  - path: /etc/cron.d/ansible-pull
    content: |
      */10 * * * * ansible /usr/bin/ansible-pull -U https://github.com/mrjohnsly/sly.dev.git -o config/ansible/server-bootstrap.yml -d /home/ansible/sly.dev >> /var/log/ansible-pull.log 2>&1
