name: Deploy Documentation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4
      - name: Cache SwiftPM packages
        uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-swiftpm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-swiftpm-
      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.2.app
      - name: Build
        run: swift build -v
      - name: Generate Documentation
        run: swift package --allow-writing-to-directory docs generate-documentation --target Server --disable-indexing --transform-for-static-hosting --hosting-base-path mrjohnsly.github.io/sly.dev --output-path docs
      - name: List contents of the docs directory
        run: ls -R docs
      - name: Upload docs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download docs artifact
        uses: actions/download-artifact@v2
        with:
          name: docs
          path: docs
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
