name: Deploy

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'config/**'
      - '**/README.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'config/**'
      - '**/README.md'

jobs:
  test:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: Set Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.3.app
    - name: Cache SwiftPM packages
      uses: actions/cache@v4
      with:
        path: .build
        key: ${{ runner.os }}-swiftpm-${{ hashFiles('**/Package.resolve') }}
        restore-keys: |
          ${{ runner.os }}-swiftpm-
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v

  build-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Swiftly
      run: |
        curl -L https://swiftlang.github.io/swiftly/swiftly-install.sh | bash -s -- --disable-confirmation
    - name: Install Swift
      run: |
        swiftly install latest --token ${{ secrets.SWIFTLY_ACCESS_TOKEN }}
    - name: Cache SwiftPM packages
      uses: actions/cache@v4
      with:
        path: .build
        key: ${{ runner.os }}-swiftpm-${{ hashFiles('**/Package.resolve') }}
        restore-keys: |
          ${{ runner.os }}-swiftpm-
    - name: Build for release
      run: |
        swift build -c release --static-swift-stdlib
    - name: Package executable and templates
      run: |
        mkdir -p .build/install
        cp -P .build/release/SlyDevServer .build/install
        cp -r Views .build/install
        tar cvzf sly.dev-0.0.1.tar.gz -C .build/install .
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: sly.dev-executable
        path: sly.dev-0.0.1.tar.gz

  deploy-to-staging:
    needs: [test, build-release]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: sly.dev-executable
      - name: Install SSH key
        env:
          SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "${SSH_KEY}" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
      - name: Add staging to known_hosts
        env:
          KNOWN_HOSTS: ${{ secrets.STAGING_KNOWN_HOSTS }}
        run: |
          echo "${KNOWN_HOSTS}" > ~/.ssh/known_hosts
      - name: Add SSH config file
        env:
          SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}
          SSH_USER: ${{ secrets.STAGING_SSH_USER }}
        run: |
          cat >>~/.ssh/config <<END
          Host $SSH_HOST
            Hostname $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking yes
          END
      - name: Copy artifact to staging server
        env:
          SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}
          SSH_PORT: ${{ secrets.STAGING_SSH_PORT }}
          SSH_USER: ${{ secrets.STAGING_SSH_USER }}
        run: |
          ssh -p $SSH_PORT $SSH_USER@$SSH_HOST <<END
            sudo mkdir -p /var/www/staging.sly.dev
            sudo chown -R $SSH_USER:$SSH_USER /var/www/staging.sly.dev
          END
          scp -P $SSH_PORT sly.dev-0.0.1.tar.gz $SSH_USER@$SSH_HOST:/var/www/staging.sly.dev
      - name: Extract artifact
        env:
          SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}
          SSH_PORT: ${{ secrets.STAGING_SSH_PORT }}
          SSH_USER: ${{ secrets.STAGING_SSH_USER }}
        run: |
          ssh -p $SSH_PORT $SSH_USER@$SSH_HOST <<END
            cd /var/www/staging.sly.dev/
            tar xvzf sly.dev-0.0.1.tar.gz --no-same-permissions
            chmod +x SlyDevServer
            sudo chown -R slydev:slydev /var/www/staging.sly.dev
            sudo chmod -R 755 /var/www/staging.sly.dev
          END
      - name: Stop app
        env:
          SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}
          SSH_PORT: ${{ secrets.STAGING_SSH_PORT }}
          SSH_USER: ${{ secrets.STAGING_SSH_USER }}
        run: |
          ssh -p $SSH_PORT $SSH_USER@$SSH_HOST <<END
            sudo systemctl stop slydevserver
          END
      - name: Start app
        env:
          SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}
          SSH_PORT: ${{ secrets.STAGING_SSH_PORT }}
          SSH_USER: ${{ secrets.STAGING_SSH_USER }}
        run: |
          ssh -p $SSH_PORT $SSH_USER@$SSH_HOST <<END
            sudo systemctl start slydevserver
          END
      - name: Check health
        run: |
          response=$(curl -o /dev/null -s -w "%{http_code}\n" https://staging.sly.dev/health)
          if [ "$response" -eq 200 ]; then
            echo "Health check passed"
          else
            echo "Health check failed"
            exit 1
          fi
  deploy-to-production:
    needs: [deploy-to-staging]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: sly.dev-executable
      - name: Install SSH key
        env:
          SSH_KEY: ${{ secrets.PRODUCTION_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "${SSH_KEY}" > ~/.ssh/production.key
          chmod 600 ~/.ssh/production.key
      - name: Add production to known_hosts
        env:
          KNOWN_HOSTS: ${{ secrets.PRODUCTION_KNOWN_HOSTS }}
        run: |
          echo "${KNOWN_HOSTS}" > ~/.ssh/known_hosts
      - name: Add SSH config file
        env:
          SSH_HOST: ${{ secrets.PRODUCTION_SSH_HOST }}
          SSH_USER: ${{ secrets.PRODUCTION_SSH_USER }}
        run: |
          cat >>~/.ssh/config <<END
          Host $SSH_HOST
            Hostname $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/production.key
            StrictHostKeyChecking yes
          END
      - name: Copy artifact to production server
        env:
          SSH_HOST: ${{ secrets.PRODUCTION_SSH_HOST }}
          SSH_PORT: ${{ secrets.PRODUCTION_SSH_PORT }}
          SSH_USER: ${{ secrets.PRODUCTION_SSH_USER }}
        run: |
          ssh -p $SSH_PORT $SSH_USER@$SSH_HOST <<END
            sudo mkdir -p /var/www/sly.dev
            sudo chown -R $SSH_USER:$SSH_USER /var/www/sly.dev
          END
          scp -P $SSH_PORT sly.dev-0.0.1.tar.gz $SSH_USER@$SSH_HOST:/var/www/sly.dev
      - name: Extract artifact
        env:
          SSH_HOST: ${{ secrets.PRODUCTION_SSH_HOST }}
          SSH_PORT: ${{ secrets.PRODUCTION_SSH_PORT }}
          SSH_USER: ${{ secrets.PRODUCTION_SSH_USER }}
        run: |
          ssh -p $SSH_PORT $SSH_USER@$SSH_HOST <<END
            cd /var/www/sly.dev/
            tar xvzf sly.dev-0.0.1.tar.gz --no-same-permissions
            chmod +x SlyDevServer
            sudo chown -R slydev:slydev /var/www/sly.dev
            sudo chmod -R 755 /var/www/sly.dev
          END
      - name: Stop server
        env:
          SSH_HOST: ${{ secrets.PRODUCTION_SSH_HOST }}
          SSH_PORT: ${{ secrets.PRODUCTION_SSH_PORT }}
          SSH_USER: ${{ secrets.PRODUCTION_SSH_USER }}
        run: |
          ssh -p $SSH_PORT $SSH_USER@$SSH_HOST <<END
            sudo systemctl stop slydevserver
            sudo rm -rf /var/lib/caddy/.local/share/caddy/
            sudo rm -rf /var/lib/caddy/.local/share/caddy/certificates/
          END
      - name: Start server
        env:
          SSH_HOST: ${{ secrets.PRODUCTION_SSH_HOST }}
          SSH_PORT: ${{ secrets.PRODUCTION_SSH_PORT }}
          SSH_USER: ${{ secrets.PRODUCTION_SSH_USER }}
        run: |
          ssh -p $SSH_PORT $SSH_USER@$SSH_HOST <<END
            sudo systemctl start slydevserver
          END
      - name: Check health
        run: |
          response=$(curl -o /dev/null -s -w "%{http_code}\n" https://sly.dev/health)
          if [ "$response" -eq 200 ]; then
            echo "Health check passed"
          else
            echo "Health check failed"
            exit 1
          fi
