name: Deploy Documentation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4
    - name: Cache SwiftPM packages
      uses: actions/cache@v4
      with:
        path: .build
        key: ${{ runner.os }}-swiftpm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-swiftpm-
    - name: Set Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.2.app
    - name: Build
      run: swift build -v
    - name: Deploy
      run: swift package --allow-writing-to-directory docs \
        generate-documentation --target Server \
        --disable-indexing \
        --transform-for-static-hosting \
        --hosting-base-path mrjohnsly.github.io/sly.dev \
        --output-path docs