name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: Set Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.3.app
    - name: Cache SwiftPM packages
      uses: actions/cache@v4
      with:
        path: .build
        key: ${{ runner.os }}-swiftpm-${{ hashFiles('**/Package.resolve') }}
        restore-keys: |
          ${{ runner.os }}-swiftpm-
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v

  build-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Swiftly
      run: |
        curl -L https://swift-server.github.io/swiftly/swiftly-install.sh | bash -s -- --disable-confirmation
    - name: Install Swift
      run: |
        swiftly install latest